# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.IntegerField(verbose_name='파일고유번호')),
                ('file_name', models.CharField(verbose_name='파일 명')),
                ('file_type', models.CharField(verbose_name='타입')),
                ('file_data', models.FileField(upload_to='uploads/', verbose_name='파일 데이터 저장')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'db_table': '"public"."file"',
            },
        ),
    ]
