# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_no', models.IntegerField(verbose_name='진행현황 순번')),
                ('no_response', models.CharField(verbose_name='미응답자')),
                ('notified', models.CharField(verbose_name='통보된 자')),
                ('schedule_coordination', models.CharField(verbose_name='일정 조율')),
                ('schedule_confirmed', models.CharField(verbose_name='일정 확정')),
                ('schedule_confirmedday', models.TimeField(verbose_name='일정 확정일')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant', verbose_name='지원자 고유번호')),
            ],
            options={
                'db_table': '"public"."progress"',
            },
        ),
    ]
