# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='사용자 고유번호')),
                ('username', models.CharField(verbose_name='사용자 명')),
                ('password', models.CharField(verbose_name='비밀번호')),
                ('email', models.CharField(verbose_name='이메일')),
                ('phone', models.CharField(verbose_name='연락처')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='부서 순번')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='직원 순번')),
            ],
            options={
                'db_table': '"public"."users"',
            },
        ),
    ]
