# Generated by Django 4.2.10 on 2024-03-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(verbose_name='사용자 고유번호'),
        ),
    ]
