# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('position', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='직원 고유번호')),
                ('start_date', models.DateField(verbose_name='입사일')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='부서 순번')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='직원 순번')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='사용자 고유번호')),
            ],
            options={
                'db_table': '"public"."employees"',
            },
        ),
    ]
