# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_id', models.IntegerField(verbose_name='순번')),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grades', verbose_name='등급 순번')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant', verbose_name='지원자 고유번호')),
            ],
            options={
                'db_table': '"public"."second_pass"',
            },
        ),
    ]
