# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.IntegerField(verbose_name='등급순번')),
                ('firstStage_grade', models.CharField(max_length=7, verbose_name='1차 등급')),
                ('secondStage_grade', models.CharField(max_length=7, verbose_name='2차 등급')),
                ('nopass', models.CharField(verbose_name='불합격')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': '"public"."grades"',
            },
        ),
    ]
