# Generated by Django 4.2.10 on 2024-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='firstStage_grade',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='1차 등급'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='secondStage_grade',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='2차 등급'),
        ),
    ]
