# Generated by Django 4.2.10 on 2024-03-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grades_firststage_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='id',
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='등급순번'),
        ),
    ]
