# Generated by Django 4.2.10 on 2024-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_grades_id_alter_grades_grade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='등급순번'),
        ),
    ]
