# Generated by Django 4.2.10 on 2024-03-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_grades_nopass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='nopass',
            field=models.CharField(blank=True, null=True, verbose_name='불합격'),
        ),
    ]
