# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_no', models.IntegerField(verbose_name='미팅순번')),
                ('meeting_name', models.CharField(verbose_name='미팅 명')),
                ('meeting_schedule', models.DateTimeField(verbose_name='미팅 일정')),
                ('meeting_type', models.CharField(verbose_name='미팅 유형')),
                ('note', models.CharField(verbose_name='비고')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
            options={
                'db_table': '"public"."meeting"',
            },
        ),
    ]
