# Generated by Django 4.2.10 on 2024-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(verbose_name='직위 순번')),
                ('position_name', models.CharField(verbose_name='직위 명')),
            ],
            options={
                'db_table': '"public"."position"',
            },
        ),
    ]
